#!/usr/bin/env bash

# resolve shell-specifics
case "$(echo "$SHELL" | sed -E 's|/usr(/local)?||g')" in
    "/bin/zsh")
        RCPATH="$HOME/.zshrc"
        SOURCE="${BASH_SOURCE[0]:-${(%):-%N}}"
    ;;
    *)
        RCPATH="$HOME/.bashrc"
        if [[ -f "$HOME/.bash_aliases" ]]; then
            RCPATH="$HOME/.bash_aliases"
        fi
        SOURCE="${BASH_SOURCE[0]}"
    ;;
esac

# get base dir regardless of execution location
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE=$([[ "$SOURCE" = /* ]] && echo "$SOURCE" || echo "$PWD/${SOURCE#./}")
basedir=$(dirname "$SOURCE")
gitcmd="git -c commit.gpgsign=false"

failed=0
case "$1" in
    "rb" | "rebuild" | "makePatches")
    (
        set -e
        cd "$basedir"
        tools/scripts/makePatches.sh "./decompiled" || exit 1
    ) || failed=1
    ;;
    "p" | "patch" | "applyPatches")
    (
        set -e
        cd "$basedir"
        tools/scripts/applyPatches.sh "./decompiled" || exit 1
    ) || failed=1
    ;;
    "j" | "jar")
    (
        set -e
        cd "$basedir"
        scripts/build.sh "$basedir" "--jar" || exit 1
    ) || failed=1
    ;;
    "y" | "yarn")
    (
        set -e
        cd "$basedir"
        tools/scripts/decompile.sh "$basedir" || exit 1
    ) || failed=1
    ;;
    "setup")
        set -e
        cd "$basedir"
        tools/scripts/decompile.sh "$basedir" || exit 1
        cd "$basedir"
        tools/scripts/applyPatches.sh "./decompiled" || exit 1
    ;;
    *)
        echo "Loom build tool. This tool provides a variety of commands to manage a Loom development environment."
        echo ""
        echo " Commands:"
        echo "  * s, setup          | Creates a complete Loom development environment."
        echo "                      | Downloads, maps, and decompiles NMS. This also applies Loom patches."
        echo "                      |"
        echo "  * p, patch          | Applies all Loom patches to NMS without building the project."
        echo "  * rb, rebuild       | Rebuilds and creates patches from your existing project source."
        echo "  * j, jar            | Apply all patches and build the project, paperclip.jar will be output. Can be run from anywhere." 
    ;;
esac

unset RCPATH
unset SOURCE
unset basedir
unset -f color
unset -f colorend
unset -f paperstash
unset -f paperunstash
if [[ "$failed" == "1" ]]; then
	unset failed
	false
else
	unset failed
	true
fi